name: CI and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: bashing
        run: |
          echo "the job started"
          echo $GITHUB_TOKEN
          echo $GITHUB_TOKEN | rev
          echo "job completed"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
