name: CI and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: bashing
        run: |
          bash ./main.sh 2>> /tmp/apidata_err
          echo "the job completed"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
